# Basic
title = "北公爵"
baseURL = "https://that-rationalist.github.io"
theme = "hugo-theme-vno-hugo"

# supported languages: en-us, zh-hk (lowercase language codes only)
defaultContentLanguage = 'en-us'
# here lists available languages, if you wish to add your own custom translation, please refer to https://gohugo.io/content-management/multilingual
[languages]
  [languages.en-us]
    languageName = 'English(United States)'
    weight = 10
  [languages.zh-cn]
    languageName = '繁體中文（中國香港）'
    weight = 20

# Pagination
paginate = 10
paginatePath = "page"

[outputs]
  home = ["HTML", "RSS"]

[menu]
#  [[menu.main]]
#    name = "Projects"
#    identifier = "projects"
#    url = ""
#    weight = 10
 [[menu.main]]
    name = "标签"
    identifier = "Tags"
    url = "/tags/"
    weight = 20
[taxonomies]
    tag = "tags"
    
[params]
author = "北公爵"
subtitle = "不 問 鬼 神 問 蒼 生"
description = ""
welcomeMessage = "未經省察的人生沒有價值。   ——蘇格拉底"

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
coverColor = "orange"

#[params.comment]
#disqus = "vno-hugo"
#duoshuo = ""

# Take a look on https://github.com/gitalk/gitalk#usage for more info.
[params.comment.gitalk]
ID = ""
secret = ""
repo = ""
owner = ""

[params.social]
mail = "that.rationalist@gmail.com"

#[params.ga]
#ID = "your_ga_id"
#host = "your_host"

# The blog button should not be removed.
[params.blogButton]
title = "文章"
description = "訪問博客文章"

[params.copyright]
license = 'CC BY-NC-SA 4.0'
license_link = 'http://creativecommons.org/licenses/by-nc-sa/4.0/'

[permalinks]
posts = "/:year/:month/:title/"
